version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: eai-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: eai_user
      MYSQL_PASSWORD: W2yY021nH3r3
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: eai-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

volumes:
  mysql-data:
